---
title: "Day 2 - Modelling"
author: "Mariachiara Fortuna"
date: "March 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries

```{r}
library(dplyr)
library(ggplot2)
```


# Data reading

```{r}
file_name <- file.path("data", "dc-wikia-data.csv")
dc <- read.csv(file_name, na.strings = "")
```


# Data trasformation

```{r}
max_year <- max(dc$YEAR, na.rm = T)

dc <- dc %>%
  mutate(activity = max_year - YEAR,
         appear = APPEARANCES)

```


# MODELING

## Linear Regression

```{r}

dc_full <- dc %>%
  select(name, appear, activity, SEX,
         ALIGN, ALIVE) %>%
  na.omit()

m1 <- lm(data = dc_full, appear ~ activity)

summary(m1)

plot(m1)

appear_residuals <- residuals(m1)

appear_pred <- predict(m1)

dc_lm <- dc_full %>%
  bind_cols(appear_m1 = appear_pred)

```


```{r}
m2 <- lm(data = dc_full, appear ~ activity + SEX)

summary(m2)
```

Sex non risulta signficativamente associata ad appear

```{r}
m3 <- lm(data = dc_full, appear ~ activity + ALIGN)

summary(m3)
```


```{r}
m4 <- lm(data = dc_full, appear ~ activity + ALIGN + activity*ALIGN)

summary(m4)
```


```{r}
ggplot(data = dc_full, aes(x = activity, y = appear)) +
  geom_point()
```

```{r}
ggplot(data = dc_full, aes(x = appear)) +
  geom_density()

ggplot(data = dc_full, aes(x = log(appear))) +
  geom_density()
```

```{r}
m4 <- lm(data = dc_full, log(appear) ~ activity + ALIGN + activity*ALIGN)

summary(m4)
```

# Cluster Analysis

```{r}
dc_cluster <- dc_full %>%
  select(appear, activity) %>%
  scale() %>%
  as.data.frame()
```


```{r}

set.seed(1234)

fit <- kmeans(dc_cluster, 4)

cluster_num <- as.factor(fit$cluster)

dc_full <- dc_full %>%
  bind_cols(cluster_val = cluster_num)

ggplot(data = dc_full, 
       aes(x = activity, y = appear, 
           col = as.factor(cluster_val))) +
  geom_point()

dc_full <- dc_full %>%
  mutate(label = case_when(
    cluster_val == 1 ~ "Star",
    cluster_val == 2 ~ "Non protagonisti",
    cluster_val == 3 ~ "Comparse",
    cluster_val == 4 ~ "Protagonisti"),
  label_fac = as.factor(label))

```


```{r}
dc_full %>%
  group_by(label_fac) %>%
  summarise(
    count = n(),
    avg_appear = mean(appear, na.rm = T),
    avg_activity = mean(activity, na.rm = T)
  )
```

```{r}
star_tab <- dc_full %>%
  filter(label_fac == "Star")
```




