---
title: "Exploratory Analysis"
author: "Mariachiara Fortuna"
date: "March 16, 2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
```



# R basics

```{r}
vec <- c(1, 2, 6)

vec

char_vec <- c("a", "b", "a", "a", "b")

fac_vec <- as.factor(char_vec)

```

# Data import

```{r}

file_name <- file.path("data", "dc-wikia-data.csv")

dc <- read.csv(file_name)

dc <- read.csv("data/dc-wikia-data.csv", na.string = "")
```

# Data exploration - Basics

```{r}
# View(dc)

str(dc)
```

# Statistiche descrittive

## Var quantitative

```{r}

min(dc$YEAR, na.rm = T)

max(dc$YEAR, na.rm = T)

range(dc$YEAR, na.rm = T)

mean(dc$APPEARANCES, na.rm = T)

sd(dc$APPEARANCES, na.rm = T)

sum(is.na(dc$APPEARANCES)) # calcolo NA
```

## Var qualitative

```{r}
table(dc$SEX)
```

## Summary

```{r}
summary(dc)
```

# Data manipulation

```{r}

dc_female <- dc %>%
  filter(SEX == "Female Characters") %>%
  select(name, SEX, ALIVE, APPEARANCES, YEAR) %>%
  arrange(desc(APPEARANCES), YEAR)

# write.csv(dc_female, "dc_female.csv")

head(dc_female)

```


```{r}
dc_female %>%
  mutate(active_years = 2013 - YEAR) %>%
  group_by(ALIVE) %>%
  summarize(avg_year = mean(active_years, na.rm = T),
            count = n())
```


# Data visualization

## One categorical var

```{r}
ggplot(data = dc, aes(x = ALIGN)) +
  geom_bar(fill = "red") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


```{r}

g1 <- ggplot(data = dc, aes(x = ALIGN, fill = SEX)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

library(plotly)

ggplotly(g1)
```